export const translateEng = {
  'ACTIVITY-START-YEAR': 'Year of the beginning of activity',
  'ADMINISTRATION': 'Leadership',
  'ADMINISTRATION-OF-KAFEDRA': 'Head of the department: ',
  'HEAD-OF-THE-DEPARTMENT': 'd.t.s., Professor Sergey Alexandrovich Subbotin',
  'DESCRIPTION-1': 'While studying at the department, students practice and learn various programming languages ​​and software design, such as C / C ++ / C #, Java, Python, PHP, PERL, JavaScript, Ruby, Matlab, R, SQL, Assembler',
  'DESCRIPTION-2': 'In addition, students will learn to use Windows, Linux, MS Office, Statistica, Mathcad, StatGraphics Plus, Adobe Photoshop, CorelDraw, IBM, WEKA, Autodesk, AutoCAD, SolidEdge, Altium Designer, PTC Creo, Atmel Studio, 1C, SVN, Git, Technology React, Vue, Angular, Node.js, ASP.net, Flutter, Laravel',
  'DESCRIPTION-3': 'There will also be an opportunity to gain skills in programming modern microcontrollers (Arduino platforms, Raspberry Pi) and developing mobile applications for Android and iOS.',
  'SPECIALITIES': 'Specialties',
  'SPECIALITY-1': '121 – «Software Engineering», educational programs',
  'SPECIALITY-1-STUDYPROGRAM': `«Software engineering»`,
  'SPECIALITY-1-DESCRIPTION': "Training of specialists whose work is related to the design, development and maintenance of software for various purposes",
  'SPECIALITY-2': "122 – «Computer Science», educational programs",
  'SPECIALITY-2-STUDYPROGRAM-1': "«Computer Science»",
  'SPECIALITY-2-STUDYPROGRAM-2': '«Artificial intelligence systems»',
  'SPECIALITY-2-DESCRIPTION': "Training of specialists in the design and implementation of computer programs, optimization, modernization and development of existing software, the use of information technology in various fields",
  'HEADER-FAQ': 'FAQ',
  'HEADER-SPECIALITIES': 'Specialties',
  'HEADER-MAIN': 'Home',
  'HEADER-DISCIPLINES': 'Disciplines',
  'HEADER-FOR-ABITURIENT': 'For the entrant',
  'HEADER-WORK': 'Employment',
  'FOOTER-ADRESS-TITLE': 'Address:',
  'FOOTER-PHONE-TITLE': 'Phone:',
  'FOOTER-EMAIL-TITLE': 'E-mail:',
  'FOOTER-ADRESS': 'str. Zhukovsky 64, Zaporozhye, Ukraine, 69063',
  'FOOTER-PHONE': '+380(61)7698267',
  'FOOTER-EMAIL': 'kafedra_pz@zntu.edu.ua',
  'FOOTER-LANGUAGE-CHANGE': 'Change the language:',
  'FOOTER-LANGUAGE-TITLE': 'Language',
  'STUDY-PRICE-TITLE': 'Cost of education',
  'STUDY-PRICE-1': 'UAH 7600 / semester + indexation',
  'STUDY-PRICE-2': 'UAH 7000 / semester + indexation',
  'FREE-PLACES-TITLE': 'Number of state-financed places.',
  'FREE-PLACES-1': '30 for junior specialists and 31 for others',
  'FREE-PLACES-2': '20 for junior specialists and 26 for others',
  'PARTNERS-TITLE': 'Partners of the department',
  'PARTNERS': `SoftServe, Computools, Freshcode, Incode Group, Infocom LTD, Light-IT, Vimeo, Absolute Web, DoneIT, Drum'N'Code, Ukrsoft Group, GroupBWT, Kozak Group, OpenGeeksLab, S-PRO, CHI Sofrware, Extrums, CUDEV, GBKSOFT, Koitechs, Logix ITS, Lumighost, Revolut LTD, Rezer Uran, Urich, PJSC "Carlsberg Ukraine", Golden Age, LLC "Silver Country", JSC "ZalK", JSC "ZalK", JSC CB "PrivatBank", DTEK Service, PJSC "Zaporizhstal" , PJSC "Motor Sich", Fozzy-group`,
  'ENTRANT-EXAM-CERTIFICATES': 'EIT certificates for admission to bachelors',
  'ENTRANT-EXAN-MAIN-SUBJECTS': 'Main subjects: Ukrainian language, Mathematics',
  'ENTRANT-EXAN-ADITIONAL-SUBJECTS': 'Electives: History of Ukraine foreign language biology | geography physics chemistry',
  'ENTRANT-EXAM-SCHEDULE-TITLE': 'EIT evaluation schedule',
  'ENTRANT-EXAM-SCHEDULE': 'Physics May 23 (Monday), Chemistry May 26 (Thursday), Ukrainian Language May 31 (Tuesday), Ukrainian Language and Literature May 31 (Tuesday), Mathematics June 3 (Friday), Spanish Language June 06 (Monday), German language June 06 (Monday), French language June 6 (Monday), English language June 7 (Tuesday), History of Ukraine June 10 (Friday), Geography June 14 (Tuesday), Biology June 17 (Friday)',
  'ENTRANT-EXAM-EXTRA-SESSION-TITLE': 'Additional session',
  'ENTRANT-EXAM-EXTRA-SESSION': 'An additional EIT session for participants who were unable to participate in the main testing session due to valid reasons will be held from June 23 to July 15, 2022.',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
}