/* eslint-disable max-len */
export const translateUkr = {
  'DEPARTMENT-NAME': 'Кафедра програмних засобів',
  'ACTIVITY-START-YEAR': 'Рiк початку дiяльностi',
  'ADMINISTRATION': 'Керiвництво',
  'ADMINISTRATION-OF-KAFEDRA': 'Завiдувач кафедри: ',
  'HEAD-OF-THE-DEPARTMENT': 'д.т.н., професор Субботiн Сергiй Олександрович',
  'TEACHERS-LINK-TITLE': 'Перелік викладачів',
  'DESCRIPTION-1': 'Під час навчання на кафедрі студенти практикують та вивчають різноманітні мови програмування та проєктування програмного забеспечення, такі як C/C++/C#, Java, Python, PHP, PERL, JavaScript, Ruby, Matlab, R, SQL, Assembler',
  'DESCRIPTION-2': 'Окрім того студенти навчаться використовувати ОС Windows, Linux, програми MS Office, Statistica, Mathcad, StatGraphics Plus, Adobe Photoshop, CorelDraw, продукти IBM, WEKA, Autodesk, AutoCAD, SolidEdge, Altium Designer, PTC Creo, Atmel Studio, 1C, SVN, Git, технології React, Vue, Angular, Node.js, ASP.net, Flutter, Laravel',
  'DESCRIPTION-3': 'Також буде можливість отримати навички програмування сучасних мікроконтролерів (платформи Arduino, Raspberry Pi) та розроблення мобільних додатків для Android та iOS.',
  'SPECIALITIES': 'Спеціальності',
  'SPECIALITY-1': '121 – «Інженерія програмного забезпечення», освітні програми',
  'SPECIALITY-1-STUDYPROGRAM': '«Інженерія програмного забезпечення»',
  'SPECIALITY-1-DESCRIPTION': 'Підготовка фахівців, робота яких пов\'язана з проєктуванням, розробленням та супроводженням програмного забеспечення різноманітного призначення',
  'SPECIALITY-2': '122 – «Комп\'ютерні науки», освітні програми',
  'SPECIALITY-2-STUDYPROGRAM-1': '«Комп\'ютерні науки»',
  'SPECIALITY-2-STUDYPROGRAM-2': '«Системи штучного інтелекту»',
  'SPECIALITY-2-DESCRIPTION': 'Підготовка фахівців з проєктування й реалізації комп\'ютерних програм, оптимізації, модернізації та розвитку наявного ПЗ, застосування інформаційних технологій у різних сферах',
  'HEADER-FAQ': 'FAQ',
  'HEADER-SPECIALITIES': 'Спеціальності',
  'HEADER-MAIN': 'Головна',
  'HEADER-STUDY-ABROAD': 'Навчання за кордоном',
  'HEADER-FOR-ABITURIENT': 'Для вступника',
  'HEADER-WORK': 'Працевлаштування',
  'FOOTER-ADRESS-TITLE': 'Адреса:',
  'FOOTER-PHONE-TITLE': 'Телефон:',
  'FOOTER-EMAIL-TITLE': 'Електронна пошта:',
  'FOOTER-ADRESS': 'вул. Жуковського 64, м. Запоріжжя, Україна, 69063',
  'FOOTER-PHONE': '+380(61)7698267',
  'FOOTER-EMAIL': 'kafedra_pz@zntu.edu.ua',
  'FOOTER-LANGUAGE-CHANGE': 'Змінити мову:',
  'FOOTER-LANGUAGE-TITLE': 'Мова',
  'STUDY-PRICE-TITLE': 'Вартість навчання',
  'STUDY-PRICE-1': '7600 грн./семестр + індексація',
  'STUDY-PRICE-2': '7000 грн./семестр + індексація',
  'FREE-PLACES-TITLE': 'Кількість бюджетних місць',
  'FREE-PLACES-1': '30 для молодших спеціалістів та 31 для інших',
  'FREE-PLACES-2': '20 для молодших спеціалістів та 26 для інших',
  'PARTNERS-TITLE': 'Партнери кафедри',
  'PARTNERS': 'SoftServe, Computools, Freshcode, Incode Group, Infocom LTD, Light-IT, Vimeo, Absolute Web, DoneIT, Drum\'N\'Code, Ukrsoft Group, GroupBWT, Kozak Group, OpenGeeksLab, S-PRO, CHI Sofrware, Extrums, CUDEV, GBKSOFT, Koitechs, Logix ITS, Lumighost, Revolut LTD, Rezer Uran, Urich, ПрАТ "Карлсберг Україна", Золотий вік, ТОВ "Срібна Країна", АТ "ЗАлК", АК КБ "ПриватБанк", ДТЕК Сервіс, ПАТ "Запоріжсталь", ПАТ "Мотор Січ", Fozzy-group',
  'ENTRANT-EXAM-CERTIFICATES': 'Сертифікати ЗНО для вступу бакалаврам',
  'ENTRANT-EXAN-MAIN-SUBJECTS': 'Основні предмети: Українська мова, Математика',
  'ENTRANT-EXAN-ADITIONAL-SUBJECTS': 'Предмети на вибір: Історія України | іноземна мова | біологія | географія | фізика | хімія',
  'ENTRANT-EXAM-SCHEDULE-TITLE': 'Графік проведення ЗНО',
  'ENTRANT-EXAM-SCHEDULE': 'Фізика 23 травня (понеділок),Хімія 26 травня (четвер),Українська мова 31 травня (вівторок),Українська мова та література 31 травня (вівторок),Математика 03 червня (п’ятниця),Іспанська мова 06 червня (понеділок),Німецька мова 06 червня (понеділок),Французька мова 06 червня (понеділок),Англійська мова 07 червня (вівторок),Історія України 10 червня (п’ятниця),Географія 14 червня (вівторок),Біологія 17 червня (п’ятниця)',
  'ENTRANT-EXAM-EXTRA-SESSION-TITLE': 'Додаткова сессія',
  'ENTRANT-EXAM-EXTRA-SESSION': 'Додаткова сесія ЗНО для учасників, які не змогли взяти участь у основній сесії тестування з поважних причин, пройде у період з 23 червня до 15 липня 2022 року',
  'EXAM-REGISTER': 'Зареєструватися на ЗНО',
  'UNIVERSITY-ENTRY-DOCUMENT-LIST-TITLE': 'Документи необхідні для вступу до університету:',
  'UNIVERSITY-ENTRY-DOCUMENT-LIST-ARRAY': [
    'Документ, що посвідчує особу;',
    'Військовий квиток або посвідчення про приписку – для військовозобов’язаних',
    'Документ державного зразка (оригінал) про раніше здобутий освітній (освітньо-кваліфікаційний) рівень, на основі якого здійснюється вступ, і додаток до нього;',
    'Сертифікат (сертифікати) зовнішнього незалежного оцінювання (для вступників на основі повної загальної середньої освіти);',
    'Документи, які підтверджують право вступника на участь у конкурсі за результатами вступних іспитів, зарахування за співбесідою, зарахування за особливими умовами вступу;чотири кольорові фотокартки розміром 3 х 4 см.',
    'Оригінали документів при участі в конкурсі на місця, що фінансуються за кошти державного бюджету, вступником подаються лише один раз при виборі місця навчання (виконання вимог до зарахування). Копії документів без пред’явлення оригіналів не розглядаються.'
  ],
  'UNIVERSITY-ENTRY-BENEFITS': 'Для абітурієнтів з пільгами',
  'UNIVERSITY-ENTRY-QUESTIONS': 'Якщо з\'явилися питання',
  'PROFESSIONS-LIST-TITLE': 'Профессії за якими випускники зможуть працевлаштуватися',
  'AVERAGE-PAYMENT': 'Середня заробітня плата:',
  'MAX-PAYMENT': 'Гранична заробітна плата:',
  'VACANCIES-NUMBER': 'Кількість вакансій:',
  'EMPLOYMENT-PARTNERS-TITLE': 'Партнери кафедри, які пропонують співпрацю студентам',
  'INTERESTING-INFO-TITLE': 'Цікаві матеріали',
  'TABLE-ENTRANT-LANGUAGE': 'Мова програмування',
  'TABLE-ENTRANT-WRITE-NOW-PERC': 'Пишуть для роботи зараз, %',
  'TABLE-ENTRANT-CHANGE': 'Зміни',
  'TABLE-ENTRANT-WRITE-NOW': 'Пишуть для роботи зараз',
  'TABLE-ENTRANT-USE-SECONDARY': 'Використовують як додаткові',
  'TABLE-ENTRANT-USE-PRIMARY': 'Використовують в своїх проектах',
  'TABLE-ENTRANT-LIKE-INDEX': 'Індекс вподобання',
  'TABLE-ENTRANT-TITLE': 'Список мов програмування та їх популярність',
  'FAQ-TITLE': 'Відповіді на розповсюджені запитання',
  'DIALOG-NAME-FIELD': 'Назва',
  'DIALOG-LINK-FIELD': 'Посилання',
  'DIALOG-HEADER-TEXT-FIELD': 'Заголовок',
  'DIALOG-MAIN-TEXT-FIELD': 'Основний текст',
  'DIALOG-HEADER-TEXT-EN-FIELD': 'Заголовок англійською',
  'DIALOG-MAIN-TEXT-EN-FIELD': 'Основний текст англійською',
  'DIALOG-INFO-FIELD': 'Информація',
  'DIALOG-INFO-EN-FIELD': 'Інформація англійською',
  'DIALOG-QUESTION-FIELD': 'Запитання',
  'DIALOG-ANSWEAR-FIELD': 'Відповідь',
  'DIALOG-QUESTION-EN-FIELD': 'Запитання англійською',
  'DIALOG-ANSWEAR-EN-FIELD': 'Відповідь англійською',
  'DIALOG-NAME-EN-FIELD': 'Назва англійською',
  'DIALOG-REQUIREMENTS-FIELD': 'Вимоги',
  'DIALOG-REQUIREMENTS-EN-FIELD': 'Вимоги англійською',
  'DIALOG-AVERAGE-PAYMENT-FIELD': 'Середня заробітня плата',
  'DIALOG-MAX-PAYMENT-FIELD': 'Максимальна заробітня плата',
  'DIALOG-VACANCIES-NUMBER-FIELD': 'Кілкість вакансій',
  'DIALOG-WRTITE-NOW-PERC-FIELD': 'Пишуть зараз %',
  'DIALOG-CHANGE-FIELD': 'Зміна',
  'DIALOG-WRITE-NOW-FIELD': 'Пишуть зараз',
  'DIALOG-USE-SEC-FIELD': 'Використовують як другу',
  'DIALOG-USE-PRIM-FIELD': 'Використовуют як основну',
  'DIALOG-INDEX-FIELD': 'Індекс оцінки',
  'ADMIN-CREATE-NEW': 'Створити новий об\'єкт',
  'ADMIN-CREATE-CONFIRM': 'Створити',
  'ADMIN-CREATE-CANCEL': 'Скасувати',
  'ADMIN-UPDATE': 'Оновити об\'єкт',
  'ADMIN-UPDATE-CONFIRM': 'Оновити',
  'ADMIN-UPDATE-CANCEL': 'Скасувати',
  'ADMIN-DELETE-CONFIRM-TITLE': 'Ви впевнені, що хочете видалити ?',
  'ADMIN-DELETE-CONFIRM': 'Видалити',
  'ADMIN-DELETE-CANCEL': 'Скасувати',
  'ADMIN-AUTH-TITLE': 'Введіть авторизаційний ключ для доступу до панелі адміністратора',
  'ADMIN-AUTH-CONFIRM': 'Підтвердити',
  'ADMIN-CREATE-BUTTON-TEXT': 'Створити',
  'ADMIN-ERROR-REQUIRED': 'Це поле є обов\'язковим',
  'ADMIN-ERROR-MIN-FIELD-LENGTH': (value) => `Мінімальна довжина поля - ${value} символи(ів)`,
  'ADMIN-ERROR-MIN-FIELD-VALUE': (value) => `Мінімальне значення поля - ${value}`,
  'ADMIN-ERROR-MAX-FIELD-VALUE': (value) => `Максимальне значення поля - ${value}`,
};