export const translateUkr = {
  'ACTIVITY-START-YEAR': 'Рiк початку дiяльностi',
  'ADMINISTRATION': 'Керiвництво',
  'ADMINISTRATION-OF-KAFEDRA': 'Завiдувач кафедри: д.т.н., професор ',
  'LABORATORIES-TO-STUDY': 'Навчальні лабораторії та майстерні',
  'LABORATORY-1': 'Навчальна лабораторія САD/САМ/САЕ',
  'LABORATORY-2': 'Навчальна лабораторія вбудованих систем та віддаленої інженерії',
  'LABORATORY-3': 'Навчальна лабораторія INTERNET технологій',
  'SPECIALITYS': 'Спеціальності',
  'SPECIALITY-1': '121 – «Інженерія програмного забезпечення», освітні програми',
  'SPECIALITY-1-STUDYPROGRAM': `«Інженерія програмного забезпечення»`,
  'SPECIALITY-2': "122 – «Комп'ютерні науки», освітні програми",
  'SPECIALITY-2-STUDYPROGRAM-1': "«Комп'ютерні науки»",
  'SPECIALITY-2-STUDYPROGRAM-2': '«Системи штучного інтелекту»',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
}