export const translateEng = {
  'ACTIVITY-START-YEAR': 'Year of the beginning of activity',
  'ADMINISTRATION': 'Leadership',
  'ADMINISTRATION-OF-KAFEDRA': 'Head of the department: ',
  'HEAD-OF-THE-DEPARTMENT': 'd.t.s., Professor Sergey Alexandrovich Subbotin',
  'TEACHERS-LINK-TITLE': 'Teachers list',
  'DESCRIPTION-1': 'While studying at the department, students practice and learn various programming languages ​​and software design, such as C / C ++ / C #, Java, Python, PHP, PERL, JavaScript, Ruby, Matlab, R, SQL, Assembler',
  'DESCRIPTION-2': 'In addition, students will learn to use Windows, Linux, MS Office, Statistica, Mathcad, StatGraphics Plus, Adobe Photoshop, CorelDraw, IBM, WEKA, Autodesk, AutoCAD, SolidEdge, Altium Designer, PTC Creo, Atmel Studio, 1C, SVN, Git, Technology React, Vue, Angular, Node.js, ASP.net, Flutter, Laravel',
  'DESCRIPTION-3': 'There will also be an opportunity to gain skills in programming modern microcontrollers (Arduino platforms, Raspberry Pi) and developing mobile applications for Android and iOS.',
  'SPECIALITIES': 'Specialties',
  'SPECIALITY-1': '121 – «Software Engineering», educational programs',
  'SPECIALITY-1-STUDYPROGRAM': '«Software engineering»',
  'SPECIALITY-1-DESCRIPTION': 'Training of specialists whose work is related to the design, development and maintenance of software for various purposes',
  'SPECIALITY-2': '122 – «Computer Science», educational programs',
  'SPECIALITY-2-STUDYPROGRAM-1': '«Computer Science»',
  'SPECIALITY-2-STUDYPROGRAM-2': '«Artificial intelligence systems»',
  'SPECIALITY-2-DESCRIPTION': 'Training of specialists in the design and implementation of computer programs, optimization, modernization and development of existing software, the use of information technology in various fields',
  'HEADER-FAQ': 'FAQ',
  'HEADER-SPECIALITIES': 'Specialties',
  'HEADER-MAIN': 'Home',
  'HEADER-STUDY-ABROAD': 'Studing abroad',
  'HEADER-FOR-ABITURIENT': 'For the entrant',
  'HEADER-WORK': 'Employment',
  'FOOTER-ADRESS-TITLE': 'Address:',
  'FOOTER-PHONE-TITLE': 'Phone:',
  'FOOTER-EMAIL-TITLE': 'E-mail:',
  'FOOTER-ADRESS': 'str. Zhukovsky 64, Zaporozhye, Ukraine, 69063',
  'FOOTER-PHONE': '+380(61)7698267',
  'FOOTER-EMAIL': 'kafedra_pz@zntu.edu.ua',
  'FOOTER-LANGUAGE-CHANGE': 'Change the language:',
  'FOOTER-LANGUAGE-TITLE': 'Language',
  'STUDY-PRICE-TITLE': 'Cost of education',
  'STUDY-PRICE-1': 'UAH 7600 / semester + indexation',
  'STUDY-PRICE-2': 'UAH 7000 / semester + indexation',
  'FREE-PLACES-TITLE': 'Number of state-financed places.',
  'FREE-PLACES-1': '30 for junior specialists and 31 for others',
  'FREE-PLACES-2': '20 for junior specialists and 26 for others',
  'PARTNERS-TITLE': 'Partners of the department',
  'PARTNERS': 'SoftServe, Computools, Freshcode, Incode Group, Infocom LTD, Light-IT, Vimeo, Absolute Web, DoneIT, Drum\'N\'Code, Ukrsoft Group, GroupBWT, Kozak Group, OpenGeeksLab, S-PRO, CHI Sofrware, Extrums, CUDEV, GBKSOFT, Koitechs, Logix ITS, Lumighost, Revolut LTD, Rezer Uran, Urich, PJSC "Carlsberg Ukraine", Golden Age, LLC "Silver Country", JSC "ZalK", JSC "ZalK", JSC CB "PrivatBank", DTEK Service, PJSC "Zaporizhstal" , PJSC "Motor Sich", Fozzy-group',
  'ENTRANT-EXAM-CERTIFICATES': 'EIT certificates for admission to bachelors',
  'ENTRANT-EXAN-MAIN-SUBJECTS': 'Main subjects: Ukrainian language, Mathematics',
  'ENTRANT-EXAN-ADITIONAL-SUBJECTS': 'Electives: History of Ukraine foreign language biology | geography physics chemistry',
  'ENTRANT-EXAM-SCHEDULE-TITLE': 'EIT evaluation schedule',
  'ENTRANT-EXAM-SCHEDULE': 'Physics July 2 (Saturday), Chemistry July 17 (Sunday), Ukrainian language June 30 (Thursday), Ukrainian language and literature June 30 (Thursday), Mathematics June 25 (Saturday), Spanish language July 06 (Wednesday), German language 06 July (Wednesday), French July 6 (Wednesday), English July 7 (Thursday), History of Ukraine July 9 (Saturday), Geography July 15 (Friday), Biology July 13 (Wednesday)',
  'ENTRANT-EXAM-EXTRA-SESSION-TITLE': 'Additional session',
  'ENTRANT-EXAM-EXTRA-SESSION': 'An additional EIT session for participants who were unable to participate in the main testing session due to valid reasons will be held from July 23 to August 11, 2022.',
  'EXAM-REGISTER': 'Register for external evaluation',
  'UNIVERSITY-ENTRY-DOCUMENT-LIST-TITLE': 'Documents required for admission to the university:',
  'UNIVERSITY-ENTRY-DOCUMENT-LIST-ARRAY': [
    'Identity document;',
    'Military ID or certificate of enlistment - for conscripts',
    'State standard document (original) on the previously obtained educational (educational and qualification) level on the basis of which the admission is made, and the appendix to it;',
    'Certificate (certificates) of external independent evaluation (for entrants on the basis of complete general secondary education);',
    'Documents confirming the entrant\'s right to participate in the competition based on the results of entrance exams, enrollment by interview, enrollment under special conditions of admission, four color photographs measuring 3 x 4 cm.',
    'The originals of documents when participating in the competition for places financed from the state budget, the applicant submits only once when choosing a place of study (fulfillment of enrollment requirements). Copies of documents without presentation of originals are not considered.'
  ],
  'UNIVERSITY-ENTRY-BENEFITS': 'For entrants with benefits',
  'UNIVERSITY-ENTRY-QUESTIONS': 'If you have any questions',
  'PROFESSIONS-LIST-TITLE': 'Professions for which graduates will be able to find employment',
  'AVERAGE-PAYMENT': 'Average salary:',
  'MAX-PAYMENT': 'Marginal wages:',
  'VACANCIES-NUMBER': 'Number of vacancies:',
  'EMPLOYMENT-PARTNERS-TITLE': 'Partners of the department who offer cooperation to students',
  'INTERESTING-INFO-TITLE': 'Interesting materials',
  'TABLE-ENTRANT-LANGUAGE': 'Programming language',
  'TABLE-ENTRANT-WRITE-NOW-PERC': 'Write to work now,%',
  'TABLE-ENTRANT-CHANGE': 'Changes',
  'TABLE-ENTRANT-WRITE-NOW': 'Write to work now',
  'TABLE-ENTRANT-USE-SECONDARY': 'Used as an add-on',
  'TABLE-ENTRANT-USE-PRIMARY': 'Use in their projects',
  'TABLE-ENTRANT-LIKE-INDEX': 'Favorite Index',
  'TABLE-ENTRANT-TITLE': 'List of programming languages and their popularity',
  'FAQ-TITLE': 'Answers to Frequently Asked Questions',
  'DIALOG-NAME-FIELD': 'Name',
  'DIALOG-LINK-FIELD': 'Link',
  'DIALOG-HEADER-TEXT-FIELD': 'Header text',
  'DIALOG-MAIN-TEXT-FIELD': 'Main text',
  'DIALOG-HEADER-TEXT-EN-FIELD': 'Header text on english',
  'DIALOG-MAIN-TEXT-EN-FIELD': 'Main text on english',
  'DIALOG-INFO-FIELD': 'Information',
  'DIALOG-INFO-EN-FIELD': 'Information on english',
  'DIALOG-QUESTION-FIELD': 'Question',
  'DIALOG-ANSWEAR-FIELD': 'Answear',
  'DIALOG-QUESTION-EN-FIELD': 'Question on english',
  'DIALOG-ANSWEAR-EN-FIELD': 'Answear on english',
  'DIALOG-NAME-EN-FIELD': 'Name on english',
  'DIALOG-REQUIREMENTS-FIELD': 'Requirements',
  'DIALOG-REQUIREMENTS-EN-FIELD': 'Requirements on english',
  'DIALOG-AVERAGE-PAYMENT-FIELD': 'Average payment',
  'DIALOG-MAX-PAYMENT-FIELD': 'Max payment',
  'DIALOG-VACANCIES-NUMBER-FIELD': 'Number of the vacancies',
  'DIALOG-WRTITE-NOW-PERC-FIELD': 'Write now, %',
  'DIALOG-CHANGE-FIELD': 'Change',
  'DIALOG-WRITE-NOW-FIELD': 'Write now',
  'DIALOG-USE-SEC-FIELD': 'Use as secondary',
  'DIALOG-USE-PRIM-FIELD': 'Use as primary',
  'DIALOG-INDEX-FIELD': 'Like index',
  'ADMIN-CREATE-NEW': 'Create new',
  'ADMIN-CREATE-CONFIRM': 'Create',
  'ADMIN-CREATE-CANCEL': 'Cancel',
  'ADMIN-UPDATE': 'Update object',
  'ADMIN-UPDATE-CONFIRM': 'Update',
  'ADMIN-UPDATE-CANCEL': 'Cancel',
  'ADMIN-DELETE-CONFIRM-TITLE': 'Are you sure you want to delete ?',
  'ADMIN-DELETE-CONFIRM': 'Delete',
  'ADMIN-DELETE-CANCEL': 'Cancel',
  'ADMIN-AUTH-TITLE': 'Please enter the authorisation code to get access to admin panel',
  'ADMIN-AUTH-CONFIRM': 'Confirm',
  'ADMIN-CREATE-BUTTON-TEXT': 'Create',
  'ADMIN-ERROR-REQUIRED': 'This field is required',
  'ADMIN-ERROR-MIN-FIELD-LENGTH': (value) => `Min field length - ${value} symbols`,
  'ADMIN-ERROR-MIN-FIELD-VALUE': (value) => `Min field value - ${value}`,
  'ADMIN-ERROR-MAX-FIELD-VALUE': (value) => `Max field value - ${value}`,
};