export const translateUkr = {
  'ACTIVITY-START-YEAR': 'Рiк початку дiяльностi',
  'ADMINISTRATION': 'Керiвництво',
  'ADMINISTRATION-OF-KAFEDRA': 'Завiдувач кафедри: ',
  'DESCRIPTION-1': 'Під час навчання на кафедрі студенти практикують та вивчают різноманітні мови програмування та проєктування програмного забеспечення, такі як C/C++/C#, Java, Python, PHP, PERL, JavaScript, Ruby, Matlab, R, SQL, Assembler',
  'DESCRIPTION-2': 'Окрім того студенти навчаться використовувати ОС Windows, Linux, програми MS Office, Statistica, Mathcad, StatGraphics Plus, Adobe Photoshop, CorelDraw, продукти IBM, WEKA, Autodesk, AutoCAD, SolidEdge, Altium Designer, PTC Creo, Atmel Studio, 1C, SVN, Git, технології React, Vue, Angular, Node.js, ASP.net, Flutter, Laravel',
  'DESCRIPTION-3': 'Також буде можливість отримати навички програмування сучасних мікроконтролерів (платформи Arduino, Raspberry Pi) та розроблення мобільних додатків для Android та iOS.',
  'SPECIALITYS': 'Спеціальності',
  'SPECIALITY-1': '121 – «Інженерія програмного забезпечення», освітні програми',
  'SPECIALITY-1-STUDYPROGRAM': `«Інженерія програмного забезпечення»`,
  'SPECIALITY-1-DESCRIPTION': "Підготовка фахівців, робота яких пов'язана з проєктуванням, розробленням та супроводженням програмного забеспечення різноманітного призначення",
  'SPECIALITY-2': "122 – «Комп'ютерні науки», освітні програми",
  'SPECIALITY-2-STUDYPROGRAM-1': "«Комп'ютерні науки»",
  'SPECIALITY-2-STUDYPROGRAM-2': '«Системи штучного інтелекту»',
  'SPECIALITY-2-DESCRIPTION': "Підготовка фахівців з проєктування й реалізації комп'ютерних програм, оптимізації, модернізації та розвитку наявного ПЗ, застосування інформаційних технологій у різних сферах",
  'HEADER-FAQ': 'FAQ',
  'HEADER-SPECIALITIES': 'Спеціальності',
  'HEADER-MAIN': 'Головна',
  'HEADER-DISCIPLINES': 'Дисципліни',
  'HEADER-FOR-ABITURIENT': 'Для вступника',
  'HEADER-TEACHERS': 'Викладачі',
  'FOOTER-ADRESS-TITLE': 'Адресса:',
  'FOOTER-PHONE-TITLE': 'Телефон:',
  'FOOTER-EMAIL-TITLE': 'Електронна пошта:',
  'FOOTER-ADRESS': 'вул. Жуковського 64, м. Запоріжжя, Україна, 69063',
  'FOOTER-PHONE': '+380(61)7698267',
  'FOOTER-EMAIL': 'kafedra_pz@zntu.edu.ua',
  'FOOTER-LANGUAGE-CHANGE': 'Змінити мову:',
  'FOOTER-LANGUAGE-TITLE': 'Мова',
  'STUDY-PRICE-TITLE': 'Вартість навчання',
  'STUDY-PRICE-1': '7600 грн./семестр + індексація',
  'STUDY-PRICE-2': '7000 грн./семестр + індексація',
  'FREE-PLACES-TITLE': 'Кількість бюджетних місць',
  'FREE-PLACES-1': '30 для молодших спеціалістів та 31 для інших',
  'FREE-PLACES-2': '20 для молодших спеціалістів та 26 для інших',
  'PARTNERS-TITLE': 'Партнери кафедри',
  'PARTNERS': `SoftServe, Computools, Freshcode, Incode Group, Infocom LTD, Light-IT, Vimeo, Absolute Web, DoneIT, Drum'N'Code, Ukrsoft Group, GroupBWT, Kozak Group, OpenGeeksLab, S-PRO, CHI Sofrware, Extrums, CUDEV, GBKSOFT, Koitechs, Logix ITS, Lumighost, Revolut LTD, Rezer Uran, Urich, ПрАТ "Карлсберг Україна", Золотий вік, ТОВ "Срібна Країна", АТ "ЗАлК", АК КБ "ПриватБанк", ДТЕК Сервіс, ПАТ "Запоріжсталь", ПАТ "Мотор Січ", Fozzy-group`,
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
}